import { Buffer } from 'node:buffer'

function requiredEnv(name) {
  const value = process.env[name]
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`)
  }
  return value
}

async function requestJson(url, init = {}) {
  const response = await fetch(url, init)
  const text = await response.text()

  let data = null
  if (text) {
    try {
      data = JSON.parse(text)
    } catch {
      data = text
    }
  }

  if (!response.ok) {
    throw new Error(
      `${init.method || 'GET'} ${url} failed (${response.status}): ${JSON.stringify(data)}`,
    )
  }

  return data
}

function tinyPngBuffer() {
  // 1x1 transparent PNG
  const base64 =
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WnLr0kAAAAASUVORK5CYII='
  return Buffer.from(base64, 'base64')
}

async function main() {
  const baseUrl = (process.env.WP_TEST_BASE_URL || 'http://localhost:3000').replace(
    /\/$/,
    '',
  )
  const token = requiredEnv('WP_API_TOKEN')
  const now = Date.now()

  const authHeaders = {
    Authorization: `Bearer ${token}`,
  }

  console.log(`Testing WP-compatible endpoints at ${baseUrl}`)

  const categories = await requestJson(
    `${baseUrl}/api/wp-json/wp/v2/categories`,
    {
      headers: authHeaders,
    },
  )
  if (!Array.isArray(categories)) {
    throw new Error('Categories response is not an array')
  }
  console.log(`- categories ok (${categories.length} returned)`)

  const postPayload = {
    slug: `wp-api-smoke-${now}`,
    title: { raw: `WP API smoke ${now}` },
    content: {
      raw: `<p>Smoke test post at ${new Date(now).toISOString()}.</p>`,
    },
    excerpt: { raw: 'Generated by scripts/test-wp-api.mjs' },
    status: 'draft',
    categories: [1],
    date: new Date(now).toISOString(),
  }
  const post = await requestJson(`${baseUrl}/api/wp-json/wp/v2/posts`, {
    method: 'POST',
    headers: {
      ...authHeaders,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(postPayload),
  })
  if (!post?.slug || !post?.id) {
    throw new Error(`Post response missing slug/id: ${JSON.stringify(post)}`)
  }
  console.log(`- posts ok (id=${post.id}, slug=${post.slug})`)

  const mediaForm = new FormData()
  mediaForm.append(
    'file',
    new Blob([tinyPngBuffer()], { type: 'image/png' }),
    `wp-api-smoke-${now}.png`,
  )
  const media = await requestJson(`${baseUrl}/api/wp-json/wp/v2/media`, {
    method: 'POST',
    headers: authHeaders,
    body: mediaForm,
  })
  if (!media?.source_url) {
    throw new Error(`Media response missing source_url: ${JSON.stringify(media)}`)
  }
  console.log(`- media ok (${media.source_url})`)

  console.log('All WP API endpoint tests passed.')
}

main().catch((error) => {
  console.error(error.message || error)
  process.exit(1)
})
